// Generated by gencpp from file serial_msgs/serial.msg
// DO NOT EDIT!


#ifndef SERIAL_MSGS_MESSAGE_SERIAL_H
#define SERIAL_MSGS_MESSAGE_SERIAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_msgs
{
template <class ContainerAllocator>
struct serial_
{
  typedef serial_<ContainerAllocator> Type;

  serial_()
    : serial()  {
    }
  serial_(const ContainerAllocator& _alloc)
    : serial(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _serial_type;
  _serial_type serial;





  typedef boost::shared_ptr< ::serial_msgs::serial_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_msgs::serial_<ContainerAllocator> const> ConstPtr;

}; // struct serial_

typedef ::serial_msgs::serial_<std::allocator<void> > serial;

typedef boost::shared_ptr< ::serial_msgs::serial > serialPtr;
typedef boost::shared_ptr< ::serial_msgs::serial const> serialConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_msgs::serial_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_msgs::serial_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace serial_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'serial_msgs': ['/home/fb/serial_success_imu/src/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::serial_msgs::serial_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_msgs::serial_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_msgs::serial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_msgs::serial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_msgs::serial_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_msgs::serial_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_msgs::serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "91402c4025b67ddb569b7ca2fb02ac79";
  }

  static const char* value(const ::serial_msgs::serial_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x91402c4025b67ddbULL;
  static const uint64_t static_value2 = 0x569b7ca2fb02ac79ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_msgs::serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_msgs/serial";
  }

  static const char* value(const ::serial_msgs::serial_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_msgs::serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] serial\n\
";
  }

  static const char* value(const ::serial_msgs::serial_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_msgs::serial_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.serial);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct serial_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_msgs::serial_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_msgs::serial_<ContainerAllocator>& v)
  {
    s << indent << "serial[]" << std::endl;
    for (size_t i = 0; i < v.serial.size(); ++i)
    {
      s << indent << "  serial[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.serial[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_MSGS_MESSAGE_SERIAL_H
